// /api/endorse-submit.js
// Public-facing endpoint for the per-clinician self-serve endorsement form.
// Distinct from /api/submit-endorsement (legacy curation form): this endpoint
// implements the verified-endorsement model — endorser_credentials,
// endorser_image_id (FK to client_image_pool), endorser_links as ordered
// array of {kind,url,label}, and display_scope ('bio_only' or 'both').
//
// Status is set to 'approved' so the endorsement renders immediately. The
// clinician is notified by email with edit/reject links bound to the
// per-row action_token (auto-generated by DB trigger). No Moonraker review.
//
// Auth model:
//   - Cookie 'mr_pt_endorsement' minted by /api/endorse-init
//   - Page token verified, contact_id derived from token, bio_material_id
//     verified to belong to that contact
//   - Per-IP rate limit (5/hour, fail-closed) — endorsement is a high-friction
//     submission, more than 5/hour is essentially always abuse
//
// Body: {
//   slug: 'practice-slug',                  // for cookie path binding
//   bio_material_id: '<uuid>',              // required
//   endorser_name: string (required),
//   endorser_credentials: string,
//   endorser_title: string,
//   endorser_org: string,
//   content: string (required, >= 10 chars),
//   endorser_image_id: '<uuid>'?            // from /api/endorse-headshot
//   endorser_image_url: string?             // cached URL from same response
//   links: [{kind, url, label?}]            // up to 5
//   include_on_homepage: boolean            // -> display_scope='both' if true
// }

var sb        = require('./_lib/supabase');
var pageToken = require('./_lib/page-token');
var rateLimit = require('./_lib/rate-limit');
var sanitizer = require('./_lib/html-sanitizer');
var monitor   = require('./_lib/monitor');

var LIMITS = {
  endorser_name:        200,
  endorser_credentials: 200,
  endorser_title:       200,
  endorser_org:         200,
  content:              5000,   // tighter than legacy 10k — keep endorsements punchy
  link_url:             1000,
  link_label:           120
};

var ALLOWED_LINK_KINDS = ['practice','psychology_today','linkedin','google_scholar','personal_site','other'];
var MAX_LINKS = 5;

var UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

module.exports = async function handler(req, res) {
  if (req.method === 'OPTIONS') {
    res.setHeader('Access-Control-Allow-Origin', 'https://clients.moonraker.ai');
    res.setHeader('Access-Control-Allow-Methods', 'POST');
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
    return res.status(200).end();
  }
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' });

  // Origin check
  var origin = req.headers.origin || '';
  if (origin && origin !== 'https://clients.moonraker.ai') {
    return res.status(403).json({ error: 'Forbidden' });
  }

  if (!sb.isConfigured())        return res.status(500).json({ error: 'Service unavailable' });
  if (!pageToken.isConfigured()) return res.status(500).json({ error: 'Service unavailable' });

  var body = req.body || {};

  // ── 1. Verify page token cookie ──────────────────────────────────
  var token = pageToken.getTokenFromRequest(req, 'endorsement');
  if (!token) return res.status(403).json({ error: 'Page token required' });
  var tokenData;
  try {
    tokenData = pageToken.verify(token, 'endorsement');
  } catch (e) {
    monitor.logError('endorse-submit', e, { detail: { stage: 'token_verify' } });
    return res.status(500).json({ error: 'Token verification unavailable' });
  }
  if (!tokenData) return res.status(403).json({ error: 'Invalid or expired page token' });
  var contactId = tokenData.contact_id;

  // ── 2. Rate limit: 5 successful submissions per hour per IP ──────
  // Fail-closed by default. Endorsements are high-intent; legitimate
  // submitters won't trip 5/hour.
  var ip = (req.headers['x-forwarded-for'] || '').split(',')[0].trim() || 'unknown';
  var rl = await rateLimit.check('endorse-submit:ip:' + ip, 5, 3600, { failClosed: true });
  rateLimit.setHeaders(res, rl, 5);
  if (!rl.allowed) {
    if (rl.reset_at) {
      res.setHeader('Retry-After', String(Math.max(1, Math.ceil((rl.reset_at - new Date()) / 1000))));
    }
    return res.status(429).json({ error: 'Too many submissions. Please try again later.' });
  }

  // ── 3. Resolve contact + slug binding ────────────────────────────
  var contact;
  try {
    contact = await sb.one(
      'contacts?id=eq.' + encodeURIComponent(contactId) +
      '&select=id,slug,practice_name,status&limit=1'
    );
  } catch (e) {
    return res.status(500).json({ error: 'Lookup failed' });
  }
  if (!contact)                                                       return res.status(403).json({ error: 'Contact not found' });
  if (['prospect','onboarding','active'].indexOf(contact.status) === -1) return res.status(403).json({ error: 'Endorsements not enabled' });

  var bodySlug = body.slug;
  if (bodySlug && !pageToken.assertSlugBinding(bodySlug, contact.slug)) {
    return res.status(403).json({ error: 'Slug mismatch' });
  }

  // ── 4. Validate required fields ──────────────────────────────────
  var clean = {};
  clean.endorser_name        = sanitizer.sanitizeText(body.endorser_name,        LIMITS.endorser_name);
  clean.endorser_credentials = sanitizer.sanitizeText(body.endorser_credentials, LIMITS.endorser_credentials);
  clean.endorser_title       = sanitizer.sanitizeText(body.endorser_title,       LIMITS.endorser_title);
  clean.endorser_org         = sanitizer.sanitizeText(body.endorser_org,         LIMITS.endorser_org);
  clean.content              = sanitizer.sanitizeText(body.content,              LIMITS.content);

  if (!clean.endorser_name)         return res.status(400).json({ error: 'Your name is required.' });
  if (!clean.content)               return res.status(400).json({ error: 'Endorsement text is required.' });
  if (clean.content.length < 10)    return res.status(400).json({ error: 'Endorsement text is too short.' });

  // ── 5. Validate bio_material_id ──────────────────────────────────
  var bioMaterialId = body.bio_material_id ? String(body.bio_material_id) : null;
  if (!bioMaterialId || !UUID_RE.test(bioMaterialId)) {
    return res.status(400).json({ error: 'Clinician selection is required.' });
  }
  var bm;
  try {
    bm = await sb.one(
      'bio_materials?id=eq.' + encodeURIComponent(bioMaterialId) +
      '&contact_id=eq.' + encodeURIComponent(contactId) +
      '&select=id,therapist_name&limit=1'
    );
  } catch (e) {
    return res.status(500).json({ error: 'Lookup failed' });
  }
  if (!bm) return res.status(400).json({ error: 'Clinician not found at this practice' });

  // ── 6. Validate optional headshot reference ──────────────────────
  var endorserImageId = null;
  var endorserImageUrl = null;
  if (body.endorser_image_id) {
    var imgId = String(body.endorser_image_id);
    if (!UUID_RE.test(imgId)) {
      return res.status(400).json({ error: 'Invalid image reference' });
    }
    var img;
    try {
      img = await sb.one(
        'client_image_pool?id=eq.' + encodeURIComponent(imgId) +
        '&contact_id=eq.' + encodeURIComponent(contactId) +
        '&category=eq.endorser_headshot' +
        '&select=id,hosted_url,storage_path,status&limit=1'
      );
    } catch (e) { img = null; }
    if (!img) {
      // Silently drop bad image ref — better to publish without headshot than 400
      endorserImageId = null;
    } else {
      endorserImageId = img.id;
      // hosted_url may be empty if cron hasn't finished optimizing yet.
      // Use the supplied URL (from upload response) as fallback so the page
      // shows something immediately. process-image-pool will overwrite the
      // file at the same path, so the URL stays valid post-optimize.
      endorserImageUrl = img.hosted_url || sanitizer.sanitizeText(body.endorser_image_url || '', 1000) || null;
    }
  }

  // ── 7. Validate links ────────────────────────────────────────────
  var safeLinks = [];
  if (Array.isArray(body.links)) {
    for (var i = 0; i < body.links.length && safeLinks.length < MAX_LINKS; i++) {
      var raw = body.links[i];
      if (!raw || typeof raw !== 'object') continue;
      var kind = String(raw.kind || 'other').toLowerCase();
      if (ALLOWED_LINK_KINDS.indexOf(kind) === -1) kind = 'other';
      var url = sanitizer.sanitizeText(raw.url || '', LIMITS.link_url);
      if (!/^https?:\/\/[^\s]{3,}$/.test(url)) continue;
      var label = sanitizer.sanitizeText(raw.label || '', LIMITS.link_label) || null;
      safeLinks.push({ kind: kind, url: url, label: label });
    }
  }

  // ── 8. Display scope ─────────────────────────────────────────────
  var displayScope = body.include_on_homepage === true ? 'both' : 'bio_only';

  // ── 9. Insert (instant publish, status='approved') ───────────────
  var insertData = {
    contact_id:           contactId,
    client_slug:          contact.slug,
    bio_material_id:      bioMaterialId,
    endorser_name:        clean.endorser_name,
    endorser_credentials: clean.endorser_credentials || null,
    endorser_title:       clean.endorser_title       || null,
    endorser_org:         clean.endorser_org         || null,
    endorser_image_id:    endorserImageId,
    endorser_headshot_url: endorserImageUrl,
    content:              clean.content,
    endorser_links:       safeLinks.length > 0 ? safeLinks : null,
    display_scope:        displayScope,
    status:               'approved',
    submitted_at:         new Date().toISOString()
  };

  var row;
  try {
    var rows = await sb.mutate('endorsements', 'POST', insertData);
    row = Array.isArray(rows) ? rows[0] : rows;
  } catch (e) {
    monitor.logError('endorse-submit', e, {
      client_slug: contact.slug,
      detail: { stage: 'insert', bio_material_id: bioMaterialId }
    });
    return res.status(500).json({ error: 'Submission failed. Please try again.' });
  }

  // Clinician notification email is sent by the cron / a separate route
  // (Layer D). Fire-and-forget here: include the action_token in the
  // response so the next layer can hook it. For now the endorsement is
  // live; the clinician will see it on the next render of the bio page.
  return res.status(201).json({
    success: true,
    id: row ? row.id : null,
    practice_name: contact.practice_name || '',
    clinician_name: bm.therapist_name || ''
  });
};
