// /api/endorse-submit.js
// Public-facing endpoint for the per-clinician self-serve endorsement form.
// Distinct from /api/submit-endorsement (legacy curation form): this endpoint
// implements the verified-endorsement model — endorser_credentials,
// endorser_image_id (FK to client_image_pool), endorser_links as ordered
// array of {kind,url,label}, and display_scope ('bio_only' or 'both').
//
// Status is set to 'approved' so the endorsement renders immediately. The
// clinician is notified by email with edit/reject links bound to the
// per-row action_token (auto-generated by DB trigger). No Moonraker review.
//
// Auth model:
//   - Cookie 'mr_pt_endorsement' minted by /api/endorse-init
//   - Page token verified, contact_id derived from token, bio_material_id
//     verified to belong to that contact
//   - Per-IP rate limit (5/hour, fail-closed) — endorsement is a high-friction
//     submission, more than 5/hour is essentially always abuse
//
// Body: {
//   slug: 'practice-slug',                  // for cookie path binding
//   bio_material_id: '<uuid>',              // required
//   endorser_name: string (required),
//   endorser_credentials: string,
//   endorser_title: string,
//   endorser_org: string,
//   content: string (required, >= 10 chars),
//   endorser_image_id: '<uuid>'?            // from /api/endorse-headshot
//   endorser_image_url: string?             // cached URL from same response
//   links: [{kind, url, label?}]            // up to 5
//   include_on_homepage: boolean            // -> display_scope='both' if true
// }

var sb        = require('./_lib/supabase');
var pageToken = require('./_lib/page-token');
var rateLimit = require('./_lib/rate-limit');
var sanitizer = require('./_lib/html-sanitizer');
var monitor   = require('./_lib/monitor');
var fetchT    = require('./_lib/fetch-with-timeout');
var email     = require('./_lib/email-template');

var BASE_URL = 'https://clients.moonraker.ai';

// slugify: lowercase, ASCII only, hyphen-separated. Strips diacritics so
// "André O'Brien" -> "andre-obrien", matching how bio_materials.slug works.
function slugify(s) {
  return String(s || '')
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^A-Za-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
    .toLowerCase()
    .substring(0, 60);   // cap so the full filename never blows past disk limits
}

var LIMITS = {
  endorser_name:        200,
  endorser_credentials: 200,
  endorser_title:       200,
  endorser_org:         200,
  content:              5000,   // tighter than legacy 10k — keep endorsements punchy
  link_url:             1000,
  link_label:           120
};

var ALLOWED_LINK_KINDS = ['practice','psychology_today','linkedin','google_scholar','personal_site','other'];
var MAX_LINKS = 5;

var UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

module.exports = async function handler(req, res) {
  if (req.method === 'OPTIONS') {
    res.setHeader('Access-Control-Allow-Origin', 'https://clients.moonraker.ai');
    res.setHeader('Access-Control-Allow-Methods', 'POST');
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
    return res.status(200).end();
  }
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' });

  // Origin check
  var origin = req.headers.origin || '';
  if (origin && origin !== 'https://clients.moonraker.ai') {
    return res.status(403).json({ error: 'Forbidden' });
  }

  if (!sb.isConfigured())        return res.status(500).json({ error: 'Service unavailable' });
  if (!pageToken.isConfigured()) return res.status(500).json({ error: 'Service unavailable' });

  var body = req.body || {};

  // ── 1. Verify page token cookie ──────────────────────────────────
  var token = pageToken.getTokenFromRequest(req, 'endorsement');
  if (!token) return res.status(403).json({ error: 'Page token required' });
  var tokenData;
  try {
    tokenData = pageToken.verify(token, 'endorsement');
  } catch (e) {
    monitor.logError('endorse-submit', e, { detail: { stage: 'token_verify' } });
    return res.status(500).json({ error: 'Token verification unavailable' });
  }
  if (!tokenData) return res.status(403).json({ error: 'Invalid or expired page token' });
  var contactId = tokenData.contact_id;

  // ── 2. Rate limit: 5 successful submissions per hour per IP ──────
  // Fail-closed by default. Endorsements are high-intent; legitimate
  // submitters won't trip 5/hour.
  var ip = (req.headers['x-forwarded-for'] || '').split(',')[0].trim() || 'unknown';
  var rl = await rateLimit.check('endorse-submit:ip:' + ip, 5, 3600, { failClosed: true });
  rateLimit.setHeaders(res, rl, 5);
  if (!rl.allowed) {
    if (rl.reset_at) {
      res.setHeader('Retry-After', String(Math.max(1, Math.ceil((rl.reset_at - new Date()) / 1000))));
    }
    return res.status(429).json({ error: 'Too many submissions. Please try again later.' });
  }

  // ── 3. Resolve contact + slug binding ────────────────────────────
  var contact;
  try {
    contact = await sb.one(
      'contacts?id=eq.' + encodeURIComponent(contactId) +
      '&select=id,slug,practice_name,status,email&limit=1'
    );
  } catch (e) {
    return res.status(500).json({ error: 'Lookup failed' });
  }
  if (!contact)                                                       return res.status(403).json({ error: 'Contact not found' });
  if (['prospect','onboarding','active'].indexOf(contact.status) === -1) return res.status(403).json({ error: 'Endorsements not enabled' });

  var bodySlug = body.slug;
  if (bodySlug && !pageToken.assertSlugBinding(bodySlug, contact.slug)) {
    return res.status(403).json({ error: 'Slug mismatch' });
  }

  // ── 4. Validate required fields ──────────────────────────────────
  var clean = {};
  clean.endorser_name        = sanitizer.sanitizeText(body.endorser_name,        LIMITS.endorser_name);
  clean.endorser_credentials = sanitizer.sanitizeText(body.endorser_credentials, LIMITS.endorser_credentials);
  clean.endorser_title       = sanitizer.sanitizeText(body.endorser_title,       LIMITS.endorser_title);
  clean.endorser_org         = sanitizer.sanitizeText(body.endorser_org,         LIMITS.endorser_org);
  clean.content              = sanitizer.sanitizeText(body.content,              LIMITS.content);

  if (!clean.endorser_name)         return res.status(400).json({ error: 'Your name is required.' });
  if (!clean.content)               return res.status(400).json({ error: 'Endorsement text is required.' });
  if (clean.content.length < 10)    return res.status(400).json({ error: 'Endorsement text is too short.' });

  // ── 5. Validate bio_material_id ──────────────────────────────────
  var bioMaterialId = body.bio_material_id ? String(body.bio_material_id) : null;
  if (!bioMaterialId || !UUID_RE.test(bioMaterialId)) {
    return res.status(400).json({ error: 'Clinician selection is required.' });
  }
  var bm;
  try {
    bm = await sb.one(
      'bio_materials?id=eq.' + encodeURIComponent(bioMaterialId) +
      '&contact_id=eq.' + encodeURIComponent(contactId) +
      '&select=id,therapist_name&limit=1'
    );
  } catch (e) {
    return res.status(500).json({ error: 'Lookup failed' });
  }
  if (!bm) return res.status(400).json({ error: 'Clinician not found at this practice' });

  // ── 6. Validate optional headshot reference ──────────────────────
  var endorserImageId = null;
  var endorserImageUrl = null;
  if (body.endorser_image_id) {
    var imgId = String(body.endorser_image_id);
    if (!UUID_RE.test(imgId)) {
      return res.status(400).json({ error: 'Invalid image reference' });
    }
    var img;
    try {
      img = await sb.one(
        'client_image_pool?id=eq.' + encodeURIComponent(imgId) +
        '&contact_id=eq.' + encodeURIComponent(contactId) +
        '&category=eq.endorser_headshot' +
        '&select=id,hosted_url,storage_path,status&limit=1'
      );
    } catch (e) { img = null; }
    if (!img) {
      // Silently drop bad image ref — better to publish without headshot than 400
      endorserImageId = null;
    } else {
      endorserImageId = img.id;
      // hosted_url may be empty if cron hasn't finished optimizing yet.
      // Use the supplied URL (from upload response) as fallback so the page
      // shows something immediately. process-image-pool will overwrite the
      // file at the same path, so the URL stays valid post-optimize.
      endorserImageUrl = img.hosted_url || sanitizer.sanitizeText(body.endorser_image_url || '', 1000) || null;
    }
  }

  // ── 7. Validate links ────────────────────────────────────────────
  var safeLinks = [];
  if (Array.isArray(body.links)) {
    for (var i = 0; i < body.links.length && safeLinks.length < MAX_LINKS; i++) {
      var raw = body.links[i];
      if (!raw || typeof raw !== 'object') continue;
      var kind = String(raw.kind || 'other').toLowerCase();
      if (ALLOWED_LINK_KINDS.indexOf(kind) === -1) kind = 'other';
      var url = sanitizer.sanitizeText(raw.url || '', LIMITS.link_url);
      if (!/^https?:\/\/[^\s]{3,}$/.test(url)) continue;
      var label = sanitizer.sanitizeText(raw.label || '', LIMITS.link_label) || null;
      safeLinks.push({ kind: kind, url: url, label: label });
    }
  }

  // ── 8. Display scope ─────────────────────────────────────────────
  var displayScope = body.include_on_homepage === true ? 'both' : 'bio_only';

  // ── 9. Insert (instant publish, status='approved') ───────────────
  var insertData = {
    contact_id:           contactId,
    client_slug:          contact.slug,
    bio_material_id:      bioMaterialId,
    endorser_name:        clean.endorser_name,
    endorser_credentials: clean.endorser_credentials || null,
    endorser_title:       clean.endorser_title       || null,
    endorser_org:         clean.endorser_org         || null,
    endorser_image_id:    endorserImageId,
    endorser_headshot_url: endorserImageUrl,
    content:              clean.content,
    endorser_links:       safeLinks.length > 0 ? safeLinks : null,
    display_scope:        displayScope,
    status:               'approved',
    submitted_at:         new Date().toISOString()
  };

  var row;
  try {
    var rows = await sb.mutate('endorsements', 'POST', insertData);
    row = Array.isArray(rows) ? rows[0] : rows;
  } catch (e) {
    monitor.logError('endorse-submit', e, {
      client_slug: contact.slug,
      detail: { stage: 'insert', bio_material_id: bioMaterialId }
    });
    return res.status(500).json({ error: 'Submission failed. Please try again.' });
  }

  if (!row || !row.id) {
    monitor.logError('endorse-submit', new Error('Insert returned no row'), {
      client_slug: contact.slug, detail: { stage: 'insert_no_row' }
    });
    return res.status(500).json({ error: 'Submission failed. Please try again.' });
  }

  // ── 10. Rename + retag the headshot pool row ─────────────────────
  // Cron processes the pool row asynchronously and reads `filename` for the
  // EXIF ImageDescription + storage path. We patch in the human-readable
  // filename + per-row exif_overrides AFTER the endorsement insert so the
  // override is keyed to a real submitted endorsement, not just an upload.
  // Pattern: <practice-slug>-<endorser-slug>-endorses-<clinician-slug>.<ext>
  // e.g. sky-therapies-maya-lin-endorses-anna-skomorovskaia.jpg
  if (endorserImageId) {
    try {
      var img = await sb.one(
        'client_image_pool?id=eq.' + encodeURIComponent(endorserImageId) +
        '&select=id,filename,storage_path,metadata_json,status&limit=1'
      );
      if (img && img.status === 'pending') {
        // Extract extension from current filename (set during sign step)
        var extMatch = (img.filename || '').match(/\.([a-z0-9]+)$/i);
        var ext = extMatch ? extMatch[1].toLowerCase() : 'jpg';

        var practiceSlug  = slugify(contact.practice_name) || contact.slug || 'practice';
        var endorserSlug  = slugify(clean.endorser_name)   || 'endorser';
        var clinicianSlug = slugify(bm.therapist_name)     || 'clinician';
        var newFilename = practiceSlug + '-' + endorserSlug + '-endorses-' + clinicianSlug + '.' + ext;

        var description = clean.endorser_name + "'s endorsement of " +
                          (bm.therapist_name || 'a clinician') +
                          (contact.practice_name ? ' at ' + contact.practice_name : '');

        await sb.mutate('client_image_pool?id=eq.' + endorserImageId, 'PATCH', {
          filename: newFilename,
          title: description,
          metadata_json: Object.assign({}, img.metadata_json || {}, {
            endorsement_id: row.id,
            exif_overrides: {
              artist: clean.endorser_name,         // endorser is the photo subject
              description: description             // human-readable EXIF ImageDescription
            }
          })
        }, 'return=minimal');
      }
    } catch (renameErr) {
      // Non-fatal — endorsement is already inserted; cron will still process
      // the image with the default Practice-as-Artist EXIF.
      monitor.logError('endorse-submit', renameErr, {
        client_slug: contact.slug,
        detail: { stage: 'pool_rename', endorsement_id: row.id, image_id: endorserImageId }
      });
    }
  }

  // ── 11. Notify the practice via Resend (best-effort) ─────────────
  // Sent to contact.email — for multi-clinician practices that's the practice
  // owner, who's the right gatekeeper for the edit/reject capability. We may
  // add bio_materials.email later for direct-to-clinician routing.
  // Failures here are non-fatal: the endorsement is live regardless.
  sendClinicianNotification({
    contact: contact,
    bm: bm,
    endorsement: row,
    cleanContent: clean.content,
    cleanEndorserName: clean.endorser_name,
    cleanEndorserCredentials: clean.endorser_credentials,
    cleanEndorserTitle: clean.endorser_title,
    cleanEndorserOrg: clean.endorser_org,
  }).catch(function (mailErr) {
    monitor.logError('endorse-submit', mailErr, {
      client_slug: contact.slug,
      detail: { stage: 'notify_clinician', endorsement_id: row.id }
    });
  });

  return res.status(201).json({
    success: true,
    id: row.id,
    practice_name: contact.practice_name || '',
    clinician_name: bm.therapist_name || ''
  });
};

// ── Notification helper ─────────────────────────────────────────────

async function sendClinicianNotification(args) {
  var contact = args.contact;
  var bm = args.bm;
  var endorsement = args.endorsement;
  if (!contact || !contact.email) return;

  var resendKey = process.env.RESEND_API_KEY;
  if (!resendKey) return;  // Soft-skip in dev / misconfigured envs

  // Refetch action_token — the trigger generates it during INSERT but PostgREST
  // won't include it unless we request it. Cheaper to refetch than complicate
  // the insert representation.
  var fresh = await sb.one(
    'endorsements?id=eq.' + encodeURIComponent(endorsement.id) +
    '&select=action_token,bio_material_id&limit=1'
  );
  var token = fresh && fresh.action_token;
  if (!token) return;

  var bioPageUrl = BASE_URL + '/' + contact.slug;            // best-guess landing
  var actionUrl  = BASE_URL + '/endorse-action/' + token;

  var endorserDisplay = args.cleanEndorserName +
    (args.cleanEndorserCredentials ? ', ' + args.cleanEndorserCredentials : '');
  var endorserContext = [args.cleanEndorserTitle, args.cleanEndorserOrg]
    .filter(Boolean).join(' at ') || '';

  var clinicianFirst = (bm && bm.therapist_name || '').split(/\s+/)[0] || 'there';
  var preview = (args.cleanContent || '').substring(0, 280) +
                (args.cleanContent && args.cleanContent.length > 280 ? '…' : '');

  var html = email.wrap({
    headerLabel: 'Peer Endorsement',
    content:
      email.greeting('Hi ' + clinicianFirst) +
      email.p('Good news. ' + args.cleanEndorserName + ' just submitted a peer endorsement for you. It\'s already live on your bio page.') +
      email.sectionHeading('What they wrote') +
      email.pRaw(
        '<div style="background:#F1F8F5;border-left:3px solid #00D47E;padding:14px 18px;border-radius:6px;margin:0 0 16px;font-style:italic;color:#333F70;line-height:1.6;font-size:15px;">' +
        email.esc(preview) +
        '</div>'
      ) +
      email.pRaw(
        '<p style="font-family:Inter,sans-serif;font-size:14px;color:#6B7599;margin:0 0 18px;">' +
        '<strong style="color:#1E2A5E;">From:</strong> ' + email.esc(endorserDisplay) +
        (endorserContext ? '<br><strong style="color:#1E2A5E;">Role:</strong> ' + email.esc(endorserContext) : '') +
        '</p>'
      ) +
      email.cta(actionUrl, 'Review, edit details, or remove') +
      email.p('You can fix typos in the endorser\'s name, title, or organization. The endorsement text itself stays as written, to keep it authentic.') +
      email.divider() +
      email.pRaw(
        '<p style="font-family:Inter,sans-serif;font-size:13px;color:#6B7599;margin:0;">' +
        'Want to see it in context? <a href="' + email.esc(bioPageUrl) + '" style="color:#00D47E;">Visit the practice site &rarr;</a>' +
        '</p>'
      ),
    footerNoteRaw: 'You\'re receiving this because someone submitted a peer endorsement for your practice. We send these so you stay in control of what appears on your pages.',
    year: new Date().getFullYear()
  });

  var resp = await fetchT('https://api.resend.com/emails', {
    method: 'POST',
    headers: { 'Authorization': 'Bearer ' + resendKey, 'Content-Type': 'application/json' },
    body: JSON.stringify({
      from: email.FROM.notifications,
      to: [contact.email],
      reply_to: 'support@moonraker.ai',
      subject: args.cleanEndorserName + ' endorsed ' + (bm.therapist_name || 'your practice'),
      html: html
    })
  }, 15000);

  if (!resp.ok) {
    var errText = '';
    try { errText = await resp.text(); } catch (_) {}
    throw new Error('Resend ' + resp.status + ': ' + String(errText).substring(0, 200));
  }
}
